const TelegramBot = require('node-telegram-bot-api');
const fs = require('fs');

// Token bot Anda
const token = '7343134460:AAFBm7UKgAxJR-_NEXWsouWdlRFHgxw8oLw';
const bot = new TelegramBot(token, { polling: true });

// Chat ID admin
const admins = ['6617099953']; // Tambahkan admin chat ID

// Fungsi untuk membaca file key.json
const loadKeyData = () => {
    try {
            const data = fs.readFileSync('key.json', 'utf8');
                    return JSON.parse(data);
                        } catch (error) {
                                console.error('Error reading key.json:', error);
                                        return null;
                                            }
                                            };

                                            // Fungsi untuk menyimpan file key.json
                                            const saveKeyData = (keyData) => {
                                                try {
                                                        fs.writeFileSync('key.json', JSON.stringify(keyData, null, 2));
                                                            } catch (error) {
                                                                    console.error('Error saving key.json:', error);
                                                                        }
                                                                        };

                                                                        // Fungsi untuk memeriksa waktu kedaluwarsa
                                                                        const checkExpiration = (expirationTimestamp) => {
                                                                            const currentTime = Math.floor(Date.now() / 1000);
                                                                                const diff = expirationTimestamp - currentTime;
                                                                                    return diff > 0 ? diff : -1; // -1 berarti sudah kedaluwarsa
                                                                                    };

                                                                                    // Fungsi untuk menghitung sisa waktu dalam format "hari, jam, menit, detik"
                                                                                    const formatTimeRemaining = (seconds) => {
                                                                                        const days = Math.floor(seconds / (24 * 3600));
                                                                                            const hours = Math.floor((seconds % (24 * 3600)) / 3600);
                                                                                                const minutes = Math.floor((seconds % 3600) / 60);
                                                                                                    const secs = seconds % 60;
                                                                                                        return `${days} hari, ${hours} jam, ${minutes} menit, ${secs} detik`;
                                                                                                        };

                                                                                                        // Perintah /start
                                                                                                        bot.onText(/\/start/, (msg) => {
                                                                                                            const chatId = msg.chat.id;
                                                                                                                const isAdmin = admins.includes(chatId.toString());

                                                                                                                    let message = 'Bot aktif dan siap digunakan!';
                                                                                                                        if (isAdmin) {
                                                                                                                                message += '\nAnda dapat menggunakan perintah /sendExp untuk memeriksa dan memperbarui waktu kedaluwarsa kunci.';
                                                                                                                                    }

                                                                                                                                        bot.sendMessage(chatId, message);
                                                                                                                                        });

                                                                                                                                        // Perintah /sendExp untuk admin
                                                                                                                                        bot.onText(/\/sendExp/, (msg) => {
                                                                                                                                            const chatId = msg.chat.id;

                                                                                                                                                // Periksa apakah pengguna adalah admin
                                                                                                                                                    if (!admins.includes(chatId.toString())) {
                                                                                                                                                            bot.sendMessage(chatId, 'Anda tidak memiliki izin untuk menggunakan perintah ini.');
                                                                                                                                                                    return;
                                                                                                                                                                        }

                                                                                                                                                                            bot.sendMessage(chatId, 'Silakan masukkan kunci yang ingin diperiksa.');
                                                                                                                                                                                bot.once('message', (response) => {
                                                                                                                                                                                        const key = response.text.trim();
                                                                                                                                                                                                const keyData = loadKeyData();

                                                                                                                                                                                                        if (!keyData || !keyData[key]) {
                                                                                                                                                                                                                    bot.sendMessage(chatId, 'Kunci tidak ditemukan.');
                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                const keyInfo = keyData[key];
                                                                                                                                                                                                                                                        const expirationDiff = checkExpiration(keyInfo.EXPIRED);

                                                                                                                                                                                                                                                                if (expirationDiff === -1) {
                                                                                                                                                                                                                                                                            bot.sendMessage(chatId, `Kunci ${key} telah kedaluwarsa.`);
                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                const timeRemaining = formatTimeRemaining(expirationDiff);
                                                                                                                                                                                                                                                                                                            bot.sendMessage(chatId, `Kunci ${key} aktif.\nModel: ${keyInfo.MODEL}\nSisa waktu: ${timeRemaining}`);

                                                                                                                                                                                                                                                                                                                        // Perbarui pesan atau kirim pesan baru ke pengguna
                                                                                                                                                                                                                                                                                                                                    bot.sendMessage(chatId, `Apakah Anda ingin memperbarui waktu kedaluwarsa kunci ${key}?`, {
                                                                                                                                                                                                                                                                                                                                                    reply_markup: {
                                                                                                                                                                                                                                                                                                                                                                        inline_keyboard: [
                                                                                                                                                                                                                                                                                                                                                                                                [
                                                                                                                                                                                                                                                                                                                                                                                                                            { text: 'Ya', callback_data: `update_${key}` },
                                                                                                                                                                                                                                                                                                                                                                                                                                                        { text: 'Tidak', callback_data: `cancel` },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Menangani tombol "Ya" dan "Tidak"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            bot.on('callback_query', (callbackQuery) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const chatId = callbackQuery.message.chat.id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const messageId = callbackQuery.message.message_id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const data = callbackQuery.data;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (data.startsWith('update_')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const key = data.split('_')[1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const keyData = loadKeyData();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!keyData || !keyData[key]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bot.answerCallbackQuery(callbackQuery.id, { text: 'Kunci tidak ditemukan.' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Tambahkan 7 hari (604800 detik) ke waktu kedaluwarsa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    keyData[key].EXPIRED += 604800;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Simpan pembaruan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    saveKeyData(keyData);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const newExpirationDiff = checkExpiration(keyData[key].EXPIRED);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const timeRemaining = formatTimeRemaining(newExpirationDiff);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            bot.editMessageText(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `Kunci ${key} berhasil diperbarui.\nSisa waktu baru: ${timeRemaining}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { chat_id: chatId, message_id: messageId }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bot.pinChatMessage(chatId, messageId).catch((err) => console.error('Error pinning message:', err));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (data === 'cancel') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bot.editMessageText('Pembaruan waktu kedaluwarsa dibatalkan.', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            chat_id: chatId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message_id: messageId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Penanganan error polling
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bot.on('polling_error', (error) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error('Polling error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });